blueprint:
  name: Alarmo to MQTT with Actions
  description: Publier un message MQTT lors d'une détection via un capteur Alarmo et inclure des actions personnalisées
  domain: automation
  input:
    alarmo_sensor:
      name: Capteur Alarmo
      description: Sélectionnez un capteur Alarmo
      selector:
        entity:
          domain: binary_sensor
    sia_number:
      name: Numéro du capteur SIA
      description: Entrez le numéro SIA pour le capteur
      default: "BA"
      selector:
        text: {}
    mqtt_topic:
      name: Sujet MQTT
      description: Entrez le sujet sur lequel publier le message MQTT
      default: 'alarme/alarme'
      selector:
        text: {}
    payload_message:
      name: Message à envoyer
      description: Entrez le message personnalisé à envoyer
      default: "Intrusion détectée par le capteur Alarmo"
      selector:
        text: {}
    qos:
      name: QoS (Qualité de Service)
      description: Sélectionnez le niveau QoS pour la publication MQTT
      default: 0
      selector:
        number:
          min: 0
          max: 2
          mode: slider
    retain:
      name: Retenir le message
      description: Choisissez si le message MQTT doit être retenu
      default: false
      selector:
        boolean: {}
    action_type:
      name: Type d'action d'Alarmo
      description: Sélectionnez le type d'action à réaliser
      selector:
        select:
          options:
            - trigger_siren
            - send_notification
            - custom_action
    custom_action_service:
      name: Service personnalisé (si "custom_action" est sélectionné)
      description: Entrez le service à appeler pour une action personnalisée
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input alarmo_sensor
    to: 'on'

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      qos: !input qos
      retain: !input retain
      payload: >
        {"sia_code": "{{ sia_code }}", "capteur": "Nri001", "message": "{{ message }}"}

  - choose:
      - conditions: "{{ action_type == 'trigger_siren' }}"
        sequence:
          - service: alarm_control_panel.alarm_trigger
            target:
              entity_id: !input alarmo_sensor
      - conditions: "{{ action_type == 'send_notification' }}"
        sequence:
          - service: notify.notify
            data:
              message: "Intrusion détectée par le capteur Alarmo"
      - conditions: "{{ action_type == 'custom_action' }}"
        sequence:
          - service: !input custom_action_service

variables:
  sia_code: !input sia_number
  message: !input payload_message

mode: single
