blueprint:
  name: Publish SIA Message
  description: Publie un message SIA sur MQTT à partir d'un capteur Alarmo
  domain: automation
  input:
    sia_number:
      name: Numéro de SIA
      description: Le numéro de capteur à envoyer.
      selector:
        number:
          min: 1
          max: 999
          mode: box

    payload_message:
      name: Message du payload
      description: Message à envoyer.
      selector:
        text: {}

trigger:
  - platform: device
    device_id: ca046768e09ac9c8aaf0e2c866b91adf
    domain: alarm_control_panel
    entity_id: 4bae2f9242f3b58aba179ee43e60bbda
    type: triggered

action:
  - service: mqtt.publish
    data:
      topic: alarme/alarme
      qos: 0
      retain: false
      payload: >
        {
          "sia_code": "BA{{ '{:03d}'.format(sia_number) }}",
          "capteur": "Nri001",
          "message": "{{ payload_message }}"
        }
mode: single
