blueprint:
  name: Publish SIA Message
  description: Publie un message SIA sur MQTT basé sur les capteurs d'Alarmo.
  domain: automation
  input:
    alarm_sensor:
      name: Capteur d'Alarmo
      description: Sélectionnez le capteur Alarmo à surveiller.
      selector:
        entity:
          domain: binary_sensor

    sia_number:
      name: Numéro de SIA
      description: Le numéro de capteur à envoyer.
      selector:
        number:
          min: 1
          max: 999
          mode: box

    payload_message:
      name: Message du payload
      description: Message à envoyer.
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input alarm_sensor
    to: 'on'  # État activé du capteur (peut être ajusté selon vos besoins)

action:
  - service: mqtt.publish
    data:
      topic: alarme/alarme
      qos: 0
      retain: false
      payload: >
        {
          "sia_code": "BA{{ '{:03d}'.format(sia_number) }}",
          "capteur": "Nri001",  # Vous pouvez personnaliser ce champ selon vos besoins
          "message": "{{ payload_message }}"
        }
