blueprint:
  name: Alarmo SIA MQTT Notification
  author: VotreNom
  description: >
    Publie un message MQTT en fonction des capteurs d'Alarmo avec un numéro SIA personnalisé.

  domain: automation
  input:
    alarmo_sensor:
      name: Alarmo Sensor
      description: >
        Sélecteur pour choisir le capteur d'Alarmo à surveiller.
      selector:
        entity:
          filter:
            - domain: binary_sensor
            - domain: sensor
          multiple: false
    mqtt_topic:
      name: MQTT Topic
      description: >
        Le topic MQTT où le message SIA sera publié.
      selector:
        text:
          multiline: false
    sia_number:
      name: SIA Number
      description: >
        Numéro SIA personnalisé pour ce capteur.
      selector:
        text:
          multiline: false
    message_template:
      name: Message Template
      description: >
        Modèle de message SIA à publier, utilisez {{ sensor_name }} pour le nom du capteur.
      selector:
        text:
          multiline: true

trigger:
  - platform: state
    entity_id: !input alarmo_sensor

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload: >
        {{ 
          (expand(!input alarmo_sensor)[0].name ~ ': ' ~ !input message_template)
          | replace('{{ sensor_name }}', expand(!input alarmo_sensor)[0].name)
          | replace('{{ sia_number }}', !input sia_number)
        }}
