blueprint:
  name: Alarmo MQTT Notifications
  description: Publie des messages MQTT basés sur des capteurs d'Alarmo.
  domain: automation
  input:
    alarmo_sensor:
      name: Capteur d'alarme
      selector:
        entity:
          domain: binary_sensor
    sia_number:
      name: Numéro SIA
      description: Numéro SIA associé au capteur.
      default: '1234'
      selector:
        text:
          max_length: 4
    mqtt_topic:
      name: Topic MQTT
      default: 'alarmo/notifications'
      selector:
        text:

trigger:
  platform: state
  entity_id: !input alarmo_sensor
  to: 'on'

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload: >
        {
          "sia_number": "{{ !input.sia_number }}",
          "sensor_name": "{{ trigger.entity_id.split('.')[1] }}",
          "message": "L'alarme a été déclenchée par {{ trigger.entity_id.split('.')[1] }}"
        }
      qos: 1
