blueprint:
  name: "Automatisation MQTT avec capteurs Alarmo"
  description: "Publie un message MQTT basé sur un capteur Alarmo avec un numéro SIA personnalisé"
  domain: automation
  input:
    sensor:
      name: "Sélectionner un capteur d'Alarmo"
      description: "Choisir un capteur configuré dans Alarmo"
      selector:
        entity:
          domain: binary_sensor
    sia_code:
      name: "Numéro SIA du capteur"
      description: "Numéro personnalisé pour le capteur qui sera utilisé dans la trame SIA"
      default: "001"
      selector:
        number:
          min: 1
          max: 999
          step: 1
    mqtt_topic:
      name: "Sujet MQTT"
      description: "Le sujet dans lequel publier le message MQTT"
      default: "alarme/alarme"
      selector:
        text:
    payload_message:
      name: "Message personnalisé"
      description: "Message à envoyer dans la trame SIA"
      selector:
        text:

trigger:
  platform: state
  entity_id: !input sensor
  to: "on"  # Déclencheur lorsque l'état du capteur passe à 'on' (ouvert/présent)

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload: >
        {
          "sia_code": "BA{{ '{:03d}'.format(!input sia_code) }}",
          "capteur": "Nri001",
          "message": "{{ states['!input sensor'].name }} : {{ !input payload_message }}"
        }
      qos: 1
      retain: true

mode: single
