blueprint:
  name: "Notification sur événement d'alarme via MQTT"
  description: "Publie un message MQTT en fonction de l'événement d'alarme sélectionné."
  domain: automation
  input:
    alarm_event:
      name: "Événement d'alarme"
      description: "Sélectionner l'événement qui déclenchera l'action."
      selector:
        select:
          options:
            - "armed"
            - "disarmed"
            - "triggered"
            - "arming"
            - "arming_failure"
            - "exit_delay"
            - "entry_delay"
    mqtt_topic:
      name: "Sujet MQTT"
      description: "Le sujet du message MQTT à publier."
      default: "home/alarm"
      selector:
        text:
    mqtt_payload:
      name: "Payload MQTT"
      description: "Le message à envoyer."
      selector:
        text:

trigger:
  platform: state
  entity_id: alarm_control_panel.home_alarm
  to: !input alarm_event

action:
  service: mqtt.publish
  data:
    topic: !input mqtt_topic
    payload: !input mqtt_payload
