blueprint:
  name: Alarmo to MQTT
  description: Publier un message MQTT lors d'une détection d'intrusion via un capteur Alarmo
  domain: automation
  input:
    alarmo_sensor:
      name: Capteur Alarmo
      description: Sélectionnez un capteur Alarmo
      selector:
        entity:
          domain: binary_sensor
    trigger_device:
      name: Appareil Déclencheur
      description: Sélectionnez l'appareil qui déclenche l'événement
      selector:
        entity:
          domain: device_tracker
    trigger_type:
      name: Type de Déclencheur
      description: Sélectionnez le type de déclencheur
      selector:
        select:
          options:
            - "Présent"
            - "Absent"
    sia_number:
      name: Numéro du capteur SIA
      description: Entrez le numéro SIA pour le capteur
      default: "BA"
      selector:
        text: {}
    mqtt_topic:
      name: Sujet MQTT
      description: Entrez le sujet sur lequel publier le message MQTT
      default: 'alarme/alarme'
      selector:
        text: {}
    payload_message:
      name: Message à envoyer
      description: Entrez le message personnalisé à envoyer
      default: "Intrusion détectée par le capteur Alarmo"
      selector:
        text: {}
    qos:
      name: QoS (Qualité de Service)
      description: Sélectionnez le niveau QoS pour la publication MQTT
      default: 0
      selector:
        number:
          min: 0
          max: 2
          mode: slider
    retain:
      name: Retenir le message
      description: Choisissez si le message MQTT doit être retenu
      default: false
      selector:
        boolean: {}

trigger:
  - platform: state
    entity_id: !input alarmo_sensor
    to: 'on'
  - platform: state
    entity_id: !input trigger_device
    to: !input trigger_type

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      qos: !input qos
      retain: !input retain
      payload: >
        {"sia_code": "{{ sia_code }}", "capteur": "Nri001", "message": "{{ message }}"}

variables:
  sia_code: !input sia_number
  message: !input payload_message

mode: single
