blueprint:
  name: Publish SIA Message
  description: Publie un message SIA sur MQTT basé sur les capteurs d'Alarmo.
  domain: automation
  input:
    alarm_sensor:
      name: Capteur d'Alarmo
      description: Sélectionnez le capteur Alarmo à surveiller.
      selector:
        entity:
          domain: binary_sensor

    sia_code:
      name: Code SIA
      description: "Le code SIA à envoyer (ex: BA003)."  # Utilisation des guillemets pour éviter les erreurs
      selector:
        text: {}

    payload_message:
      name: Message du payload
      description: "Message à envoyer."  # Utilisation des guillemets pour éviter les erreurs
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input alarm_sensor
    to: 'on'  # État activé du capteur (ajustez selon vos besoins)

action:
  - service: mqtt.publish
    data:
      topic: alarme/alarme
      qos: 0
      retain: false
      payload: >
        {
          "sia_code": "{{ sia_code }}",
          "capteur": "Nri001",  # Ajustez ce champ si nécessaire
          "message": "{{ payload_message }}"
        }
mode: single
