blueprint:
  name: Notification Frigate
  description: |
    ## Notification de l'application Frigate

    Ce blueprint enverra une notification via MQTT lorsqu'un événement Frigate pour la caméra sélectionnée est déclenché. La notification inclura un lien vers le clip vidéo.

  domain: automation
  input:
    camera:
      name: Caméra Frigate
      description: Le nom de la caméra tel que défini dans votre configuration frigate.
    mqtt_topic:
      name: Topic MQTT
      description: Le topic MQTT sur lequel envoyer la notification.
    base_url:
      name: (Optionnel) URL de base
      description: >
        L'URL externe de votre instance Home Assistant. Cela s'ouvrira dans l'application plutôt que dans le navigateur.
      default: ""

mode: parallel
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: "{{ camera }}/new"
    value_template: "{{ value_json['after']['camera'] }}"

action:
  - alias: "Notification d'événement Frigate"
    sequence:
      - variables:
          id: "{{ trigger.payload_json['after']['id'] }}"
          object: "{{ trigger.payload_json['after']['label'] }}"
          label: "{{ object | title }}"
      - service: mqtt.publish
        data:
          topic: !input mqtt_topic
          payload: "Un {{ label }} a été détecté sur la caméra {{ camera }}. Clip vidéo: {{ base_url }}/api/frigate/notifications/{{ id }}/{{ camera }}/clip.mp4"
